[phases.setup]
nixPkgs = ["python312", "nodejs_22"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "pip install -r requirements.txt",
  "npm --prefix chainlink install --omit=dev"
]

[start]
cmd = "python dash.py"
